#!/usr/bin/env python3
"""
convert_opts_to_strict_prod.py

Production-grade converter for Polyspace .opts files generated by polyspace-configure.

Purpose
-------
Create a strict reproduction options file where:
  - Each command option is written one per line.
  - -options-for-sources and the adjacent source file value are removed.
  - All -I / -D / -U options from all -options-for-sources blocks are extracted.
  - Duplicate -I / -D / -U options are removed globally while preserving first-seen order.
  - Global options such as -sources, -lang, -compiler, -target, etc. are preserved.
  - A diagnostics report and log file are generated.

Example
-------
python convert_opts_to_strict_prod.py C:\\Xilinx\\testxi.opts -o test_strict.txt

Then run:
polyspace-bug-finder -options-file test_strict.txt
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from collections import Counter, OrderedDict, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


VERSION = "1.0.0"

SOURCE_EXTENSIONS = (".c", ".cc", ".cpp", ".cxx", ".c++", ".C")


class ConversionStats:
    def __init__(self) -> None:
        self.total_lines = 0
        self.comment_lines = 0
        self.blank_lines = 0
        self.options_for_sources_blocks = 0
        self.sources_seen: List[str] = []
        self.global_options_count = 0
        self.extracted_counts = Counter()
        self.duplicate_counts = Counter()
        self.malformed_blocks: List[str] = []
        self.conflicting_defines: Dict[str, List[str]] = defaultdict(list)
        self.missing_include_paths: List[str] = []
        self.missing_source_paths: List[str] = []


def configure_logging(log_file: Path, verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        handlers=[
            logging.FileHandler(log_file, encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )


def normalise_for_dedup(option: str, case_insensitive_paths: bool) -> str:
    """
    Dedup key.
    For Windows path-heavy projects, include path case can vary. By default this script
    keeps exact text. If --case-insensitive-paths is enabled, -I paths are matched case-insensitively.
    """
    stripped = option.strip()
    if case_insensitive_paths and stripped.startswith("-I"):
        return stripped.lower()
    return stripped


def add_unique(
    ordered: OrderedDict,
    option: str,
    stats: ConversionStats,
    kind: str,
    case_insensitive_paths: bool,
) -> None:
    option = option.strip()
    if not option:
        return

    key = normalise_for_dedup(option, case_insensitive_paths)
    stats.extracted_counts[kind] += 1

    if key in ordered:
        stats.duplicate_counts[kind] += 1
    else:
        ordered[key] = option


def split_semicolon_options(line: str) -> List[str]:
    """
    polyspace-configure writes -options-for-sources as semicolon-separated tokens.
    This intentionally does not split on spaces because macro values may contain spaces, e.g.
      -D __CHAR16_TYPE__=short unsigned int
    """
    return [token.strip() for token in line.strip().split(";") if token.strip()]


def parse_options_for_sources(
    line: str,
    include_opts: OrderedDict,
    define_opts: OrderedDict,
    undef_opts: OrderedDict,
    stats: ConversionStats,
    case_insensitive_paths: bool,
) -> None:
    stats.options_for_sources_blocks += 1

    tokens = split_semicolon_options(line)
    if not tokens:
        stats.malformed_blocks.append(line[:300])
        return

    first = tokens[0]
    prefix = "-options-for-sources"

    if not first.startswith(prefix):
        stats.malformed_blocks.append(line[:300])
        return

    source_file = first[len(prefix):].strip()
    if source_file:
        stats.sources_seen.append(source_file)
    else:
        stats.malformed_blocks.append(line[:300])

    # Skip token[0] because it is: -options-for-sources <source-file>
    for token in tokens[1:]:
        if token.startswith("-I"):
            add_unique(include_opts, token, stats, "-I", case_insensitive_paths)
        elif token.startswith("-D"):
            add_unique(define_opts, token, stats, "-D", case_insensitive_paths)
        elif token.startswith("-U"):
            add_unique(undef_opts, token, stats, "-U", case_insensitive_paths)
        else:
            # Strict source-specific reproduction focuses on -I/-D/-U only because these
            # are the source-specific compile context options produced in this section.
            logging.debug("Ignored non -I/-D/-U token inside -options-for-sources: %s", token)


def define_name_and_value(option: str) -> Tuple[str, str]:
    """
    Parses -D forms:
      -D NAME=VALUE
      -DNAME=VALUE
      -D NAME
      -DNAME
    Returns (NAME, VALUE). VALUE is empty if not provided.
    """
    body = option[2:].strip()
    if "=" in body:
        name, value = body.split("=", 1)
        return name.strip(), value.strip()
    return body.strip(), ""


def detect_conflicting_defines(define_options: Iterable[str], stats: ConversionStats) -> None:
    values_by_name: Dict[str, set] = defaultdict(set)

    for opt in define_options:
        name, value = define_name_and_value(opt)
        if name:
            values_by_name[name].add(value)

    for name, values in values_by_name.items():
        if len(values) > 1:
            stats.conflicting_defines[name] = sorted(values)


def path_after_include(option: str) -> str:
    return option[2:].strip().strip('"')


def path_after_sources(option: str) -> str:
    return option[len("-sources"):].strip().strip('"')


def check_paths(
    include_options: Iterable[str],
    global_options: Iterable[str],
    stats: ConversionStats,
    enable_path_checks: bool,
) -> None:
    if not enable_path_checks:
        return

    for inc in include_options:
        path_text = path_after_include(inc)
        # Ignore macros/environment variables because they cannot be resolved reliably here.
        if path_text and "$" not in path_text and "%" not in path_text:
            if not Path(path_text).exists():
                stats.missing_include_paths.append(path_text)

    for opt in global_options:
        if opt.startswith("-sources"):
            source_path = path_after_sources(opt)
            if source_path and "$" not in source_path and "%" not in source_path:
                if not Path(source_path).exists():
                    stats.missing_source_paths.append(source_path)


def write_output(
    output_file: Path,
    include_opts: OrderedDict,
    define_opts: OrderedDict,
    undef_opts: OrderedDict,
    global_options: List[str],
    input_file: Path,
) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with output_file.open("w", encoding="utf-8", newline="\n") as out:
        out.write("# ============================================================\n")
        out.write("# Strict Polyspace options file\n")
        out.write(f"# Generated by convert_opts_to_strict_prod.py v{VERSION}\n")
        out.write(f"# Input: {input_file}\n")
        out.write(f"# Generated: {timestamp}\n")
        out.write("# ============================================================\n\n")

        out.write("# ---- Include paths extracted from -options-for-sources ----\n")
        for opt in include_opts.values():
            out.write(f"{opt}\n")
        out.write("\n")

        out.write("# ---- Defines extracted from -options-for-sources ----\n")
        for opt in define_opts.values():
            out.write(f"{opt}\n")
        out.write("\n")

        out.write("# ---- Undefines extracted from -options-for-sources ----\n")
        for opt in undef_opts.values():
            out.write(f"{opt}\n")
        out.write("\n")

        out.write("# ---- Global Polyspace options preserved from input ----\n")
        for opt in global_options:
            out.write(f"{opt}\n")


def write_diagnostics(
    diagnostics_file: Path,
    input_file: Path,
    output_file: Path,
    log_file: Path,
    stats: ConversionStats,
    include_opts: OrderedDict,
    define_opts: OrderedDict,
    undef_opts: OrderedDict,
    global_options: List[str],
) -> None:
    with diagnostics_file.open("w", encoding="utf-8", newline="\n") as out:
        out.write("# Polyspace .opts Conversion Diagnostics\n\n")
        out.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        out.write("## Files\n")
        out.write(f"- Input: `{input_file}`\n")
        out.write(f"- Output: `{output_file}`\n")
        out.write(f"- Log: `{log_file}`\n\n")

        out.write("## Summary\n")
        out.write(f"- Total lines read: {stats.total_lines}\n")
        out.write(f"- Comment lines skipped: {stats.comment_lines}\n")
        out.write(f"- Blank lines skipped: {stats.blank_lines}\n")
        out.write(f"- `-options-for-sources` blocks found: {stats.options_for_sources_blocks}\n")
        out.write(f"- Source files seen in source-specific blocks: {len(stats.sources_seen)}\n")
        out.write(f"- Global options preserved: {len(global_options)}\n")
        out.write(f"- Unique `-I`: {len(include_opts)} / extracted {stats.extracted_counts['-I']} / duplicates removed {stats.duplicate_counts['-I']}\n")
        out.write(f"- Unique `-D`: {len(define_opts)} / extracted {stats.extracted_counts['-D']} / duplicates removed {stats.duplicate_counts['-D']}\n")
        out.write(f"- Unique `-U`: {len(undef_opts)} / extracted {stats.extracted_counts['-U']} / duplicates removed {stats.duplicate_counts['-U']}\n\n")

        out.write("## Source files listed inside `-options-for-sources` blocks\n")
        if stats.sources_seen:
            for src in stats.sources_seen:
                out.write(f"- {src}\n")
        else:
            out.write("- None found\n")
        out.write("\n")

        out.write("## Conflicting `-D` definitions\n")
        if stats.conflicting_defines:
            out.write("These macro names appeared with more than one value. Review before relying on strict output.\n\n")
            for name, values in stats.conflicting_defines.items():
                out.write(f"- `{name}`: {', '.join('`' + v + '`' for v in values)}\n")
        else:
            out.write("- No conflicting `-D` definitions detected.\n")
        out.write("\n")

        out.write("## Malformed `-options-for-sources` blocks\n")
        if stats.malformed_blocks:
            for block in stats.malformed_blocks:
                out.write(f"- `{block}`\n")
        else:
            out.write("- None detected.\n")
        out.write("\n")

        out.write("## Missing include paths detected on this machine\n")
        if stats.missing_include_paths:
            for p in stats.missing_include_paths:
                out.write(f"- `{p}`\n")
        else:
            out.write("- None detected, or path checks were not enabled.\n")
        out.write("\n")

        out.write("## Missing source paths detected on this machine\n")
        if stats.missing_source_paths:
            for p in stats.missing_source_paths:
                out.write(f"- `{p}`\n")
        else:
            out.write("- None detected, or path checks were not enabled.\n")


def convert(args: argparse.Namespace) -> int:
    input_file = Path(args.input).expanduser().resolve()
    output_file = Path(args.output).expanduser().resolve()
    log_file = Path(args.log).expanduser().resolve()
    diagnostics_file = Path(args.diagnostics).expanduser().resolve()

    configure_logging(log_file, args.verbose)

    logging.info("Polyspace .opts strict converter v%s", VERSION)
    logging.info("Input: %s", input_file)
    logging.info("Output: %s", output_file)

    if not input_file.exists():
        logging.error("Input file does not exist: %s", input_file)
        return 2

    include_opts: OrderedDict[str, str] = OrderedDict()
    define_opts: OrderedDict[str, str] = OrderedDict()
    undef_opts: OrderedDict[str, str] = OrderedDict()
    global_options: List[str] = []
    stats = ConversionStats()

    with input_file.open("r", encoding=args.encoding, errors="replace") as f:
        for raw_line in f:
            stats.total_lines += 1
            line = raw_line.strip()

            if not line:
                stats.blank_lines += 1
                continue

            if line.startswith("#"):
                stats.comment_lines += 1
                continue

            if line.startswith("-options-for-sources"):
                parse_options_for_sources(
                    line,
                    include_opts,
                    define_opts,
                    undef_opts,
                    stats,
                    args.case_insensitive_paths,
                )
            else:
                global_options.append(line)
                stats.global_options_count += 1

    detect_conflicting_defines(define_opts.values(), stats)
    check_paths(include_opts.values(), global_options, stats, args.check_paths)

    write_output(output_file, include_opts, define_opts, undef_opts, global_options, input_file)
    write_diagnostics(
        diagnostics_file,
        input_file,
        output_file,
        log_file,
        stats,
        include_opts,
        define_opts,
        undef_opts,
        global_options,
    )

    logging.info("Unique -I options: %d", len(include_opts))
    logging.info("Unique -D options: %d", len(define_opts))
    logging.info("Unique -U options: %d", len(undef_opts))
    logging.info("Global options preserved: %d", len(global_options))
    logging.info("Diagnostics: %s", diagnostics_file)
    logging.info("Done")

    if stats.conflicting_defines:
        logging.warning("Conflicting -D definitions detected: %d", len(stats.conflicting_defines))
    if stats.malformed_blocks:
        logging.warning("Malformed -options-for-sources blocks detected: %d", len(stats.malformed_blocks))
    if args.check_paths and (stats.missing_include_paths or stats.missing_source_paths):
        logging.warning("Missing paths detected. Review diagnostics file.")

    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert Polyspace .opts to a strict one-option-per-line Polyspace options file.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("input", help="Input .opts file generated by polyspace-configure")
    parser.add_argument("-o", "--output", default="test_strict.txt", help="Output Polyspace options .txt file")
    parser.add_argument("--log", default="convert_opts_to_strict.log", help="Log file")
    parser.add_argument("--diagnostics", default="convert_opts_to_strict_diagnostics.md", help="Diagnostics report file")
    parser.add_argument("--encoding", default="utf-8", help="Input file encoding")
    parser.add_argument(
        "--check-paths",
        action="store_true",
        help="Check whether include and source paths exist on the current machine",
    )
    parser.add_argument(
        "--case-insensitive-paths",
        action="store_true",
        help="Deduplicate -I paths case-insensitively. Useful on Windows.",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Enable verbose debug logging")
    return parser


def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()
    return convert(args)


if __name__ == "__main__":
    raise SystemExit(main())
